### ISSUE TITLE
Gemfile database adapter detection fails on new Rails/bundler

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1157]
Upon upgrading to the latest stable Rails, I have found that our mechanism for conditionally including mysql and postgres gems in the Gemfile is not working as expected. To reproduce this, simple upgrade Rails/bundler/et al and issue the command `bundle update mysql2`. Bundler will say there is no such gem.

**Comment by augustf** [comment]
We're not going to be able to upgrade gems much further without hitting this bug, so I've designated it a blocker for future releases.

**Comment by augustf** [comment]
@mfrederickson Are you seeing this issue anymore?

**Comment by mfrederickson** [comment]
Yes, I see the same problem that you report in the original message above.

**Comment by mfrederickson** [comment]
It is in the production group, does that matter? I tried in my development environment.

**Comment by augustf** [comment]
Yeah-I don't think they're supposed to show up in development mode. This should be a production mode issue.

**Comment by mfrederickson** [comment]
Yeah, I suppose. But I run some of my other projects in mysql2 in dev.  Anyway when I prefix it with RAILS_ENV=production I still get the problem.

**Comment by mfrederickson** [comment]
I've seen a comment that says their fix was to remove the Gemfile.lock and try again.  I tried this and that solution worked for me.  This makes sense to me when you think about it-- that gem is only getting included in production and since the Gemfile.lock is produced by the developer and checked in, it's getting locked out (so to speak).  I might be grossly misunderstanding this.  If so please let me know.  I suppose I'd fix this by always including that gem regardless of environment.

**Comment by augustf** [comment]
So it turns out that issues related to this have been breaking the build for some time. I never received the email, and so only found out now. I've tried to mend the Gemfile.lock with no success. I think the next step will be to move my last 2 commits out to a branch and revert them from master until some solution is found.
