### ISSUE TITLE
Manual rake db:migrate fails for lack of devise secret key

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1203]
@mfrederickson Despite the change we did in e14d3ae736bcd14c5bd10473e1b660b667733866 , when I run a manual migration, I get 

```
Devise.secret_key was not set. Please add the following to your Devise initializer:
```

**Comment by mfrederickson** [comment]
Yes, it's messed up [though I don't get any devise messages].  For some reason performing the migrations through the app works, but manually does not-- though I get different messages than you.  I'm going to need to spend some time researching this.

Of note also is that there are some warnings that get output when I attempt the rake
```
concerto/lib/tasks/frontentjs.rake:3: warning: already initialized constant DEBUG_NONE
concerto/lib/tasks/frontentjs.rake:3: warning: previous definition of DEBUG_NONE was here
concerto/lib/tasks/frontentjs.rake:4: warning: already initialized constant DEBUG_NORMAL
concerto/lib/tasks/frontentjs.rake:4: warning: previous definition of DEBUG_NORMAL was here
concerto/lib/tasks/frontentjs.rake:5: warning: already initialized constant DEBUG_SUPER
concerto/lib/tasks/frontentjs.rake:5: warning: previous definition of DEBUG_SUPER was here
```
Also, it seems that it is checking for the existence of the database twice?
```
db/test.sqlite3 already exists
db/test.sqlite3 already exists
You have 65 pending migrations:
  20100220021335 CreateContents
...
```
And when you attempt another migration immediately after this, it gives you a timeout because the flag file is still there.
```
 RAILS_ENV=test rake db:migrate
rake aborted!
Timeout::Error: execution expired

ll tmp/migration_tempfile 
-rw-rw-r-- 1 mfrederickson mfrederickson 0 Apr  6 08:43 tmp/migration_tempfile
```

**Comment by mfrederickson** [comment]
Is there a way that we can make the automatic database setup in the 01-initializer not run if it running because of a `rake db:` call?  (Because why run it automatically when it's being explicitly run?)

**Comment by augustf** [comment]
@mfrederickson  The general problem you're referring to is contention on that DB initializer. It could also be a webserver starting multiple threads of Concerto or someone opening multiple tabs on a non-installed Concerto.

In the general case, this code is a primitive attempt at resolving that: https://github.com/concerto/concerto/blob/master/config/initializers/01-db_create_load_or_migrate.rb#L46

**Comment by augustf** [comment]
@mfrederickson I found just such a way in 40a26b5f229cb87ebf196ed79ef57e2544d7539c . Perhaps it may be helpful.
