### ISSUE TITLE
Support UTF-8 encoded XSLT

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1323]
From the mailing list:
Concerto apparently doesn't like XSLT tweaked RSS feeds that use UTF-8 encoding.  I've beat my head off and on the last couple of days trying to figure out how to fix it.  Since I can't, I just edited my XSLT to use ASCII encoding only:

<xsl:output indent="yes" method="xml" encoding="ASCII" omit-xml-declaration="yes" />

**Comment by mfrederickson** [comment]
@augustf I don't think this is still a problem-- but if you find otherwise, please provide the feed and template you are using.

![selection_158](https://cloud.githubusercontent.com/assets/473165/26667593/693990f0-4652-11e7-8b5a-d46ce0201b7a.png)

![selection_159](https://cloud.githubusercontent.com/assets/473165/26667599/70409588-4652-11e7-91d7-a012282d4f00.png)
