### ISSUE TITLE
Repeating content on frontend

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1329]
We've had quite a few reports on the mailing list about content in the rotation repeating. The post ( https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/concerto-digital-signage/xtWKhTK4k9o) and some follow-up emails have been able to confirm this is happening.

mfrederickson says "probably something in the frontend or the caching.  The next step to take I think is to write a simple ruby script that pulls content down from the server (just for the graphics field) to see if it repeats from a simple client. One of the emails in that chain lists how to pull back the list of content in the order it should be coming in. (rails console code using the base shuffle)"

**Comment by mikldt** [comment]
After staring at for this a bit, I'm thinking the issue is related to timeline data being stored in the session. I used the server address shared on the mailing list as an example, rather than trying to reproduce locally. Tracing through the list of requests to contents.json in the developer console in chrome, I occasionally saw two requests in a row using the same hashed session_id cookie. It turned out that these were requests that were overlapping: the second started before the first finished. Here is a simplified hypothetical example:

```
request frontend/10/fields/5/contents.json with cookie0 -> set cookie1
request frontend/10/fields/1/contents.json with cookie1 -> set cookie2   got a new image
request frontend/10/fields/2/contents.json with cookie2 -> set cookie3   cookie3 contains the advanced field 2 timeline
request frontend/10/fields/3/contents.json with cookie2 -> set cookie4   request started before previous request completed, so it uses the old cookie, cookie2.
request frontend/10/fields/5/contents.json with cookie4 -> set cookie5
```

When requests from separate fields coincidentally overlap, the nice request-to-request chain of cookies is broken. Looking at the [code](https://github.com/concerto/concerto/blob/master/app/controllers/frontend/contents_controller.rb#L19), I think Concerto assumes that each request will have the session cookie set by the previous request, and does not account for overlapping or nearly-simultaneous requests.

Each session cookie contains the current state of the timeline for all the fields on the screen. Therefore the fact that field 2 was updated to the next content is stored in cookie 3 but lost after that because it is written over with cookie4, which was based on cookie2 but not cookie3 because both requests occurred simultaneously. Field 3's timeline is advanced but the next time field 2 comes around, it is like the previous request had never happened.

Note that if all content across a screen's fields has the same length, fields are likely to go in and out of phase with each other. This means that at some times the issue will be occurring on nearly every content, and at other times may be hardly noticeable. This may explain some of why this has seemed so intermittent. The issue is probably exacerbated by the use of the cookie store  for sessions, and probably by the response speed of the server.

Rough thoughts on where to go from here:

1. Possible workaround: switch to DB Session Store. Server deals with less latency and has its own concurrency limits, which should either lessen or eliminate the issue.

2. Another hack may be to make the Javascript operate one request at a time. I have no idea if this is possible with Polymer, but is probably not desirable unless other alternatives fail.

2. One way to fix this without a complete overhaul is to store the data for each field in a different cookie, rather than putting it into the session cookie. For each request, the server would only send the set-cookie header for the cookie corresponding to the field that is being requested. Note: if taking this approach, make sure we've taken security steps similar to what Rails does for the session cookie.

3. Rather than storing the whole session server-side, we could consider decoupling timelines from the session and storing them in the DB or other server cache  (though this is DB or memory intensive)

4. Bigger picture approach: If we are generating the whole timeline in advance, why are we bothering to have the client request it one item at a time? Unless I'm missing something big, we should consider sending the whole timeline worth of content meta-data down to the client at once, and then having it come back to content.json when it has exhausted the timeline. This way the field is stateless outside of the timeline stored in the client.
