### ISSUE TITLE
Display to user if they are submitting to two feeds that are shown on the same screen

### ISSUE THREAD

**Issue by ddbruce** [concerto/concerto#1335]
This is to prevent redundancy of content. For instance, if I submit to the "Service and Community" and the "Career Development" feeds, it should let me know that both feeds are displayed concurrently on at least one of the screens.

Alternatively, it should be possible (if it's not already) to restrict each piece of content to one display period per screen. That is, if a screen displays multiple feeds and if a piece of content is on multiple of those feeds, the screen should view the content as if it only appears once, so to not give the content twice, thrice, or more viewing time.

On a related note: I have no clue if things moderated already appear on screens for the feed I'm currently moderating. All in all, it's not very intuitive. Contact me for more details and examples.

**Comment by mikldt** [comment]
Leaving myself a note to consider this for #1331 - I like the idea of limiting this in the shuffling algorithm - give each content the priority of the highest-priority thread it is submitted to, but no more than that.

Overall I think this is probably something we don't want to concern the submitter with, because it is confusing, but also because a good user acting in enlightened self-interest user could take advantage of that to increase their playtime unreasonably.

Another thought might be to make sure that the approval process gives them visibility into what other feeds things have been submitted to / approved on. That way someone moderating the business school feed might say "This is good content, but I don't feel bad rejecting it because it should be approved and displayed on my screen by the athletics feed moderators".

**Comment by mfrederickson** [comment]
Closed with #1331.
