### ISSUE TITLE
Error when upgrading to 2.3.3 "Gem::Ext::BuildError: ERROR: Failed to build gem native extension."

### ISSUE THREAD

**Issue by robp2175** [concerto/concerto#1339]
```
    `Installing nokogiri 1.6.7.2 with native extensions

    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby2.1 extconf.rb
    checking if the C compiler accepts ... yes
    Building nokogiri using packaged libraries.
    Using mini_portile version 2.0.0
    checking for gzdopen() in -lz... yes
    checking for iconv... yes
    ************************************************************************
    IMPORTANT NOTICE:

    Building Nokogiri with a packaged version of libxml2-2.9.2
    with the following patches applied:
            - 0001-Revert-Missing-initialization-for-the-catalog-module.patch
            - 0002-Fix-missing-entities-after-CVE-2014-3660-fix.patch
            - 0003-Stop-parsing-on-entities-boundaries-errors.patch
            - 0004-Cleanup-conditional-section-error-handling.patch
            - 0005-CVE-2015-1819-Enforce-the-reader-to-run-in-constant-.patch
            - 0006-Another-variation-of-overflow-in-Conditional-section.patch
            - 0007-Fix-an-error-in-previous-Conditional-section-patch.patch
            - 0008-CVE-2015-8035-Fix-XZ-compression-support-loop.patch
            - 0009-Updated-config.guess.patch
            - 0010-Fix-parsering-short-unclosed-comment-uninitialized-access.patch
            - 0011-Avoid-extra-processing-of-MarkupDecl-when-EOF.patch
            - 0012-Avoid-processing-entities-after-encoding-conversion-.patch
            - 0013-CVE-2015-7497-Avoid-an-heap-buffer-overflow-in-xmlDi.patch
            - 0014-CVE-2015-5312-Another-entity-expansion-issue.patch
            - 0015-Add-xmlHaltParser-to-stop-the-parser.patch
            - 0016-Detect-incoherency-on-GROW.patch
            - 0017-CVE-2015-7500-Fix-memory-access-error-due-to-incorre.patch
            - 0018-CVE-2015-8242-Buffer-overead-with-HTML-parser-in-pus.patch
            - 0019-Do-not-print-error-context-when-there-is-none.patch
            - 0020-xmlStopParser-reset-errNo.patch
            - 0021-Reuse-xmlHaltParser-where-it-makes-sense.patch

    Team Nokogiri will keep on doing their best to provide security
    updates in a timely manner, but if this is a concern for you and want
    to use the system library instead; abort this installation process and
    reinstall nokogiri as follows:

        gem install nokogiri -- --use-system-libraries
            [--with-xml2-config=/path/to/xml2-config]
            [--with-xslt-config=/path/to/xslt-config]

        If you are using Bundler, tell it to use the option:

        bundle config build.nokogiri --use-system-libraries
        bundle install

    Note, however, that nokogiri is not fully compatible with arbitrary
    versions of libxml2 provided by OS/package vendors.
    ************************************************************************
    Extracting libxml2-2.9.2.tar.gz into tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.2... OK
    Running git apply with /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.7.2/patches/libxml2/0001-Revert-Missing-initialization-for-the-catalog-module.patch... ERROR, review '/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.7.2/ext/nokogiri/tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.2/patch.log' to see what happened. Last lines are:
    ========================================================================
    fatal: Not a git repository: ../../../../.git/modules/concerto_full/usr/share/concerto
    ========================================================================
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

    Provided configuration options:
            --with-opt-dir
            --without-opt-dir
            --with-opt-include
            --without-opt-include=${opt-dir}/include
            --with-opt-lib
            --without-opt-lib=${opt-dir}/lib
            --with-make-prog
            --without-make-prog
            --srcdir=.
            --curdir
            --ruby=/usr/bin/ruby2.1
            --help
            --clean
            --use-system-libraries
            --enable-static
            --disable-static
            --with-zlib-dir
            --without-zlib-dir
            --with-zlib-include
            --without-zlib-include=${zlib-dir}/include
            --with-zlib-lib
            --without-zlib-lib=${zlib-dir}/lib
            --enable-cross-build
            --disable-cross-build
    /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:366:in `block in execute': Failed to complete patch task (RuntimeError)
            from /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:337:in `chdir'
            from /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:337:in `execute'
            from /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:71:in `block in apply_patch'
            from /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:81:in `call'
            from /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:81:in `apply_patch'
            from /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:87:in `block in patch'
            from /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:85:in `each'
            from /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:85:in `patch'
            from /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:148:in `cook'
            from extconf.rb:289:in `block (2 levels) in process_recipe'
            from extconf.rb:182:in `block in chdir_for_build'
            from extconf.rb:181:in `chdir'
            from extconf.rb:181:in `chdir_for_build'
            from extconf.rb:288:in `block in process_recipe'
            from extconf.rb:187:in `tap'
            from extconf.rb:187:in `process_recipe'
            from extconf.rb:478:in `<main>'

    extconf failed, exit code 1

    Gem files will remain installed in /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.7.2 for inspection.
    Results logged to /usr/share/concerto/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.7.2/gem_make.out
    Using rack-test 0.6.3
    Installing warden 1.2.5
    Using mail 2.6.3
    Installing airbrake 5.0.3
    Using ruby-ll 2.1.2
    Installing bundler-audit 0.4.0
    Using coffee-script 2.4.1
    Using uglifier 2.7.2
    Installing faraday 0.9.2
    Using logging 2.0.0
    Installing representable 2.3.0
    Using sprockets 2.11.3
    Installing font-awesome-sass 4.5.0
    Using rubinius-actor 0.0.2
    Using therubyracer 0.12.2
    Installing simplecov 0.11.1
    Installing activesupport 4.2.5.1
    An error occurred while installing nokogiri (1.6.7.2), and Bundler cannot
    continue.
    Make sure that `gem install nokogiri -v '1.6.7.2'` succeeds before bundling.
    dpkg: error processing package concerto-full (--configure):`
```

**Comment by xd1936** [comment]
We are getting a similar error on a clean install of Ubuntu 14.04 server as well :(

**Comment by augustf** [comment]
As a rule, we can't guarantee our Debian package working on an Ubuntu system. There are quite a lot of package dependency and naming differences that shift regularly. That said, this looks like a nokogiri library dependency issue (nokogiri is flaky even on my Mac). I might start by looking around on the nokogiri bug tracker for more information on this error. I'll leave this open for awhile to give one of us a chance to run this on an Ubuntu VM and attempt a temporary fix of some kind.

**Comment by ronkkrop** [comment]
I'm getting the exact same error message and I'm using Debian 8.5 (Jessie):

Oddly, If I run: gem install nokogiri -v '1.6.7.2'
it will run without issue...This has me confuzzled.
If you are using Bundler, tell it to use the option:                                                                                                         

    bundle config build.nokogiri --use-system-libraries                                                                                                      
    bundle install                                                                                                                                           

Note, however, that nokogiri is not fully compatible with arbitrary                                                                                          
versions of libxml2 provided by OS/package vendors.                                                                                                          
************************************************************************                                                                                     
Extracting libxml2-2.9.2.tar.gz into tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.2... OK                                                                       
Running git apply with /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.7.2/patches/libxml2/0001-Revert-Missing-initialization-for-the-catalog-module.patch... ERROR, review '/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.7.2/ext/nokogiri/tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.2/patch.log' to see what happened. Last lines are:                                                                                                               
========================================================================                                                                                     
fatal: Not a git repository: ../../../../.git/modules/concerto_full/usr/share/concerto                                                                       
========================================================================                                                                                     
*** extconf.rb failed ***                                                                                                                                    
Could not create Makefile due to some reason, probably lack of necessary                                                                                     
libraries and/or headers.  Check the mkmf.log file for more details.  You may                                                                                
need configuration options.                                                                                                                                  

Provided configuration options:                                                                                                                              
























/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:366:in `block in execute': Failed to complete patch task (RuntimeError)                                                                                                                                           


















To see why this extension failed to compile, please check the mkmf.log which can be found here:                                                              

  /usr/share/concerto/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.7.2/mkmf.log                                                       

extconf failed, exit code 1                                                                                                                                  

Gem files will remain installed in /usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.7.2 for inspection.                                        
Results logged to /usr/share/concerto/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.7.2/gem_make.out                                   
Using rack-test 0.6.3
Using warden 1.2.5
Using mail 2.6.3
Using airbrake 5.0.3
Using ruby-ll 2.1.2
Using bundler-audit 0.4.0
Using coffee-script 2.4.1
Using uglifier 2.7.2
Using faraday 0.9.2
Using logging 2.0.0
Using representable 2.3.0
Using sprockets 2.11.3
Using font-awesome-sass 4.5.0
Using rubinius-actor 0.0.2
Using therubyracer 0.12.2
Using simplecov 0.11.1
Using activesupport 4.2.5.1
An error occurred while installing nokogiri (1.6.7.2), and Bundler cannot
continue.                                                                                                                                                    
Make sure that `gem install nokogiri -v '1.6.7.2'` succeeds before bundling.

**Comment by lo-windigo** [comment]
Can confirm what ronkkrop is reporting; we are working with the same setup and receiving the exact same results.

**Comment by augustf** [comment]
Is anyone still having this issue? My first impression is that it's a difference in system libxml use/detection.

**Comment by esambo** [comment]
I got that same nokogiri error too: `~/.gem/ruby/2.3.3/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:366:in 'block in execute': Failed to complete compile
task (RuntimeError)` and was able to fix it by **opening Xcode** which prompted me to install additional stuff. I am on the latest macOS (with all App Store updates installed) and homebrew (`brew update && brew upgrade`)

**Comment by mfrederickson** [comment]
I've had a **similar** issue when trying to update a plugin that kept failing and was able to resolve it by running `bundle update nokogiri` and then the plugin update succeeded.

**Comment by augustf** [comment]
https://github.com/concerto/concerto/pull/1381/files#diff-e79a60dc6b85309ae70a6ea8261eaf95R198
