### ISSUE TITLE
date format in JSON String malformed, when using other locale then "en"

### ISSUE THREAD

**Issue by jheyens** [concerto/concerto#1340]
Hi,

Just found a small bug. When adding Content, attaching to a feed causes errors if the user locale has been set to "de". 
The reason for this is the date format automatically inserted into "Start displaying" and "Finish displaying" respects the users choice of locale. This date format is directly put into the JSON-String send to the server without being reformatted. It then is not able to parse the date because it expects "MM/DD/YYYY" instead of "DD.MM.YYYY"
[http://pastebin.com/raw/fivuWi01](url)

€: BTW: Happens with official debian jessie packages and from a session build source.

**Comment by mfrederickson** [comment]
I believe that a partial fix for the problem above is to change the contents.rb around line 98 and 110 like this, so that it uses the date format from the translation file:
```
      # t = DateTime.strptime("#{_start_time[:date]} #{_start_time[:time]}", "%m/%d/%Y %l:%M %p")
      t = DateTime.strptime("#{_start_time[:date]} #{_start_time[:time]}", "#{I18n.t('time.formats.date_long_year')} %l:%M %p")
```

But there is also the problems that the datepicker doesn't respect the locale like it should (month names, and resulting date format once a date has been selected)

![image](https://cloud.githubusercontent.com/assets/473165/23317872/9b6068fa-fa7c-11e6-8e17-583635856e22.png)

and the timepicker also does not populate the list properly and cannot be converted back into the model without erroring.

![image](https://cloud.githubusercontent.com/assets/473165/23317922/d5d47120-fa7c-11e6-83be-dc8b89b6dfcc.png)

**Comment by mfrederickson** [comment]
from application.js
```
//  NOTE: right now only the English (default) is provided for the bootstrap-datepicker; if all internationalizations should be included, just remove the '/core' part of the line above and make it just 'require bootstrap-datepicker'
```

**Comment by Xeondile** [comment]
hi at all,
I tried to fix that problem by my own. It was a little bit more work than I thought. But I thing I made it.
For testing I used the concerto image and made a full update and upgrade to last version 2.3.5

apt-get update
apt-get upgrade

After that I edit a bunch of files, see the attachment.

Hope that will help some people, and is a solution for further updates.

[concerto fix language support.txt](https://github.com/concerto/concerto/files/1334034/concerto.fix.language.support.txt)

**Comment by mfrederickson** [comment]
@Xeondile thanks for sharing (too bad it wasn't a PR).  I'll create a PR for this soon and get it included in the next release, pending testing results of course-- but it looks good so far.

**Comment by Xeondile** [comment]
@mfrederickson sorry i am not so firm in using github. PR = Pull Request? It is a while ago I wrote the fix, but I remember that I have issues with other plugins in german, I fixed them also, but have not documented the steps. Looking forward to a new release so I can test it again, I thing it was "Concerto Template Scheduling" or "Concerto Content Scheduling", maybe both.
