### ISSUE TITLE
OVA VirtualBox Package not fully pre-setup

### ISSUE THREAD

**Issue by EpicLPer** [concerto/concerto#1348]
The build I downloaded today seems to not be fully set up, I tried booting it up and connecting to the webserver but all I get is a whole load of errors that something with Ruby would not be correct.

http://pastebin.com/ehBCrups

**Comment by augustf** [comment]
This looks like an error with Faraday (the component Concerto uses to connect to Github for plugin information) being unable to get a connection. Is the VM running Concerto properly networked with permission to make outgoing Internet connections? 

—
August

On September 1, 2016 at 7:45:53 AM, EpicLPer (notifications@github.com) wrote:

The build I downloaded today seems to not be fully set up, I tried booting it up and connecting to the webserver but all I get is a whole load of errors that something with Ruby would not be correct.

http://pastebin.com/ehBCrups

**Comment by EpicLPer** [comment]
Heya,

sorry, no, the VM had no internet connection at this point. I thought that the whole point of the VM image would be to not need any internet connection anymore, sorry.

**Comment by augustf** [comment]
On our community mailing list, there are a number of question from folks trying to use Concerto offline or in a restricted Intranet environment. It is possible, but because of the nature of our plugins (nearly all of which use the Internet to retrieve data), it tends not to be a useful way to use Concerto. But if you look at those posts, you'll find some pointers for modifying Concerto to cooperate.
