### ISSUE TITLE
Content Cycling in Chrome

### ISSUE THREAD

**Issue by kmarcinko** [concerto/concerto#1365]
I am running Concerto-Full 2.3.3 on Ubuntu Server 16.04.1.  When viewing our concerto page in Chrome, content will not change unless you refresh the page.  We also had the issue described in ticket 1361.  This issue does not occur in Firefox or Safari.

I have tried updating the plugins as it says there are updates available.  I get a message saying the Frontend has updated successfully but the version number doesn't change and it still says "Upgrade Available".

**Comment by snoop168** [comment]
So i have the same problem... I solved it by doing the following commands:
bundle update concerto_frontend
RAILS_ENV=production bundle exec rake assets:precompile
sudo service apache2 restart

after running the bundle update command you may want to 'chown' the files to make sure the web server is the owner since running the commands in command line will probably make the terminal user the owner of the files... 

So i think the update functionality within the GUI is broken is there real problem here..

**Comment by augustf** [comment]
One small issue with bundle update is that despite the arguments passed, it has a habit of updating other things too. I've found it safer to alter Gemfile.lock carefully to your desired version and then do the rest.

**Comment by snoop168** [comment]
after altering the gemfile.lock what would be the command to update per the specifications in that file?

**Comment by mfrederickson** [comment]
@snoop168 it would be `bundle install`.  Personally, I don't mess with the Gemfile.lock file, I would just put the version in the Gemfile file or the plugin specific one Gemfile-plugin that gets included.  I believe that the Gemfile.lock file gets created/rewritten when `bundle install` or `bundle update` are run.

**Comment by mfrederickson** [comment]
#1376 should help with this problem of plugins not getting upgraded since it provides feedback.  I think this ticket can be closed. @kmarcinko did you get it working?

**Comment by augustf** [comment]
https://github.com/concerto/concerto/pull/1376
