### ISSUE TITLE
Change X-Frame-Options to Allowall or a specific host

### ISSUE THREAD

**Issue by robp2175** [concerto/concerto#1476]
X-Frame-Options are set to sameorigin by default. How and where do I change this in the concerto files. Thank you for any assistance.

**Comment by mfrederickson** [comment]
Looking at this, it appears that you can set it in the apache configuration file for your concerto site.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by mfrederickson** [comment]
@robp2175 I also found that it is set to ALLOWALL in the code here:
https://github.com/concerto/concerto/blob/master/app/controllers/contents_controller.rb#L339
But that seems to only be set for previewing content (during the add content process).
https://github.com/concerto/concerto/blob/master/app/controllers/contents_controller.rb#L4

So since you are seeing  SAMEORIGIN, it looks like the apache config may be the solution needed here.  Or you could remove the `, only: :preview` on line 4, but I'm not sure of the security implications of doing so.  You'd have to restart apache, of course.

**Comment by robp2175** [comment]
Setting it in Apache would not work for me. However, I did find the solution, I had to edit

 ```
/usr/share/concerto/config/application.rb
```
and add this line
```
config.action_dispatch.default_headers.merge!({'X-Frame-Options' => 'ALLOWALL'})
```
Thank you Marvin, I appreciate your help.
