### ISSUE TITLE
Docker images status?

### ISSUE THREAD

**Issue by sirtet** [concerto/concerto#1488]
The info in the wiki seems outdated/old...
Can something new be said about the status of the effort to create a docker image?

I am not familiar with using docker in general, but i did manage to run some other docker images on a Synology NAS, where i'd like now to get a concerto instance running.

**Comment by randyarrasmith** [comment]
I started playing with concerto yesterday.  I am also interested in the docker images.  Yesterday I downloaded the vm image and ran it in vmware just so I could play with concerto and get familiar with it.  The product seems good; their docs are horrible :(  
Today I tried the docker side of things because that is an easier way of installing and managing (IMO).... and I also have a Synology NAS that will be a great place to run it from.  I was surprised the concerto-full doesn't actually exist, the concerto-base only has an unstable tag and it looks like it was done a year ago.  However, I was pleasantly surprised going with the base image and installing a mysql docker image first, then the base, IT WORKED.  I am not sure how concerto found the mysql image but it did.  (It survives a reboot and has all my added data)
I am glad I played with concerto yesterday in the vm so I was familiar with it and was able to tell that the docker image is working also.  Actually the docker seemed better because it had 7 plugins and the vm only had 1 preinstalled.
Hopefully, if more people use concerto and comment about it they will be encouraged to update the docs and the docker images :)

**Comment by patchbank** [comment]
> Hopefully, if more people use concerto and comment about it they will be encouraged to update the docs and the docker images :)

Thats the wrong way of thinking. Not many people can use it, because the documentation is garbage. We weren't able to get the docker container working. Volume mounts aren't working properly either. Also the VM image doesn't work for us.

They need to update their docs properly so people actually can use it.

**Comment by mfrederickson** [comment]
@kench can you give me access to the concerto docker organization so I can provide another image?

**Comment by mfrederickson** [comment]
@patchbank @randyarrasmith @sirtet I'd be much obliged if you guys can test out the new docker image (building it yourself via the directions in the readme) and let me know how it goes.
