### ISSUE TITLE
Ruby Gem error invalid option: --no-ri

### ISSUE THREAD

**Issue by ajohnpeters** [concerto/concerto#1507]
I had to update several packages when install debian package of conceto. I updated to gem to the latest version 3.06  because of a bug not finding gem. I now get the error 
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-ri
dpkg: error processing package concerto-full (--configure):
 installed concerto-full package post-installation script subprocess returned error exit status 1

**Comment by mfrederickson** [comment]
I think you'll have better luck with 
```
cd concerto
gem install bundler -v '1.17.3'
bundle _1.17.3_ install --path=vendor/bundle
```

Because the current deb packages are outdated, it would be best to build the docker image and run that, as explained in the README-- or at least look at the Dockerfile to see how to install it manually (on Ubuntu).  If you really want to install it on the latest Debian instead, you could look at the docker files under the concerto-debian repo to see what needs to be done.  Just be aware that these docker images use master (which is waiting to be released) and not the latest release.
