### ISSUE TITLE
Apparent memory leak

### ISSUE THREAD

**Issue by apetherick** [concerto/concerto#565]
We run concerto 2 on some screens on campus, and it appears there is a memory leak in the frontend. 
After a few days of running , the screens need refreshing because the chromium tab process runs out of memory (He's Dead Jim).

Any thoughts?

**Comment by augustf** [comment]
#1078 should obsolete this.

**Comment by hkparker** [comment]
Sorry for the delay getting back to you guys.  For the last several months we haven't been keeping up with upgrades, we locked down a working-enough version and put it on the back burner due to the persistent problems on the pis.  Now that this looks fixed we've created a clone of the server that is up to date (2.2.7), and we're moving some of our clients over to that.  Hopefully in a week or two I can report back with memory usage graphs on the updated clients and confirm no leak.

**Comment by kench** [comment]
I appreciate any and all data points regarding the new frontend code.

**Comment by hkparker** [comment]
Version 2.2.7 has no changes over 2.1.0, the memory leak behaves the same.  The brief downtime in this graph is the transition to the new front end code.

![screen shot 2015-04-24 at 12 23 35 pm](https://cloud.githubusercontent.com/assets/2918615/7327024/c880f4cc-ea7e-11e4-819b-c1ecdd34db7d.png)

**Comment by augustf** [comment]
@hkparker My earlier comment on #1078 was actually in reference to the new concerto-frontend gem. The current frontend has not been maintained in quite some time as we prepare for the new Polymer-based one, which should be going into testing shortly.

**Comment by hkparker** [comment]
It looks like that is part of the 2.3 milestone, so will versions >= 2.3 serve the new modular front end in the same way?  Or is there going to need to be some client side configuration for the newer version?
